debug and trace level added to help set up the plugin.
NaturalHistoryMuseum/ckanext-ldap pull request #27
Opened 2018-01-24 01:14 UTC by kartikbha

debug and trace level added to help set up the plugin. This will also help to trace who is log in to the system.

2018-01-24 14:08 UTC, jrdh requested changes
I've requested a couple of changes (see in line review comments), additionally, could you include the `trace_level` parameter in the [other initialize usage](https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/master/ckanext/ldap/controllers/user.py#L309)
 and then move the `ldap.set_option(ldap.OPT_DEBUG_LEVEL, ...)` code to the start of the file so that it always happens and only happens once?

2018-01-24 14:08 UTC, jrdh commented on ckanext/ldap/controllers/user.py
> +       cnx = ldap.initialize(config['ckanext.ldap.uri'], bytes_mode=False,config['ckanext.ldap.trace_level'])
This currently won't run as you have a positional argument after a keyword one (`SyntaxError: non-keyword arg after keyword arg`).

2018-01-24 14:08 UTC, jrdh commented on ckanext/ldap/plugin.py
> +            'ckanext.ldap.trace_level': {'default': '0'}
These could be defined as `{'default': 0, 'parse': p.toolkit.asint}` then you don't have to check the value in the code, you can just use it.

2018-01-25 06:15 UTC, kartikbha commented
issue in code so, closing

2018-01-25 06:15 UTC, closed without merging